"""empty message

Revision ID: 38f92c5b82ce
Revises: da2cf897ad19
Create Date: 2021-07-20 23:59:23.136960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da2cf897ad19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Price',
    sa.Column('itemid', sa.String(length=100), nullable=False),
    sa.Column('minprice', sa.Integer(), nullable=True),
    sa.Column('maxprice', sa.Integer(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('itemid')
    )
    op.create_table('Shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop', sa.String(length=10), nullable=True),
    sa.Column('URLform', sa.String(length=150), nullable=True),
    sa.Column('IURLform', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop')
    )
    op.create_table('Itemname',
    sa.Column('itemid', sa.String(length=30), nullable=False),
    sa.Column('itemname', sa.String(length=150), nullable=True),
    sa.Column('shopid', sa.Integer(), nullable=True),
    sa.Column('priceid', sa.String(length=100), nullable=True),
    sa.Column('imageurl', sa.String(length=150), nullable=True),
    sa.Column('itemurl', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['priceid'], ['Price.itemid'], ),
    sa.ForeignKeyConstraint(['shopid'], ['Shop.id'], ),
    sa.PrimaryKeyConstraint('itemid')
    )
    op.drop_table('itemname')
    op.drop_index('shop', table_name='shop')
    op.drop_table('shop')
    op.drop_table('price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price',
    sa.Column('itemid', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('minprice', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('maxprice', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('itemid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('shop',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('URLform', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('IURLform', mysql.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('shop', 'shop', ['shop'], unique=False)
    op.create_table('itemname',
    sa.Column('itemid', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('itemname', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('shopid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priceid', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('imageurl', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('itemurl', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['priceid'], ['price.itemid'], name='itemname_ibfk_1'),
    sa.ForeignKeyConstraint(['shopid'], ['shop.id'], name='itemname_ibfk_2'),
    sa.PrimaryKeyConstraint('itemid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Itemname')
    op.drop_table('Shop')
    op.drop_table('Price')
    # ### end Alembic commands ###
